services:
  app:
    build: .
    volumes:
      - sqlite_data:/db
    environment:
      - NODE_ENV=development
    command: >
      sh -c "mkdir db && make migrate && make start"
    ports:
      - "3003:3003"

volumes:
  sqlite_data: {} 